# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20161112_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='photos.Category'),
            preserve_default=False,
        ),
    ]
