# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='dummy', max_length=100)),
                ('project_contributor', models.CharField(max_length=500)),
                ('task_list', models.CharField(max_length=500)),
                ('date_marker', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='progress',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.Project'),
        ),
    ]
