# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='category_', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller_name', models.CharField(default='controller_', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(default='member_', max_length=100)),
                ('member_department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='task_', max_length=100)),
                ('task_members', models.ManyToManyField(to='ProjectManager.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_name', models.CharField(default='workspace_', max_length=100)),
                ('workspace_controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.Controller')),
            ],
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='project_name',
            new_name='progress_project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='date_marker',
            new_name='project_start_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_contributor',
        ),
        migrations.RemoveField(
            model_name='project',
            name='task_list',
        ),
        migrations.AddField(
            model_name='progress',
            name='progress_name',
            field=models.CharField(default='progress_', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='project_', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='task_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.Project'),
        ),
        migrations.AddField(
            model_name='progress',
            name='progress_task',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.Task'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_controller',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.Controller'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_members',
            field=models.ManyToManyField(to='ProjectManager.Member'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_workspaces',
            field=models.ManyToManyField(to='ProjectManager.Workspace'),
        ),
    ]
