# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0002_auto_20161212_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='controller_description',
            field=models.CharField(default='test workspace_', max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.CharField(blank=True, default='test project_', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='workspace_description',
            field=models.CharField(blank=True, default='test workspace_', max_length=300, null='True'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_department',
            field=models.CharField(blank=True, choices=[('project manager', 'project manager'), ('team manager', 'team manager'), ('freelancer', 'freelancer')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_members',
            field=models.ManyToManyField(blank=True, null=True, to='ProjectManager.Member'),
        ),
    ]
