# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0003_auto_20161213_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='progress_gauge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_department',
            field=models.CharField(choices=[('project manager', 'project manager'), ('team manager', 'team manager'), ('freelancer', 'freelancer')], default='undesignated', max_length=100),
        ),
        migrations.AlterField(
            model_name='progress',
            name='progress_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.Task'),
        ),
    ]
