# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0004_auto_20161213_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_department',
            field=models.CharField(choices=[('project manager', 'project manager'), ('team manager', 'team manager'), ('freelancer', 'freelancer'), ('backend programmer', 'backend programmer'), ('frontend programmer', 'frontend programmer')], default='undesignated', max_length=100),
        ),
    ]
