# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0005_auto_20161213_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
