# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0006_auto_20161214_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.Category'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.Task'),
        ),
    ]
