# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0008_auto_20161214_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
