# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0009_task_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.BooleanField(default=False),
        ),
    ]
