# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0010_task_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_initiated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='task_submitter',
            field=models.CharField(blank=True, default='Anonymous', max_length=100, null=True),
        ),
    ]
