# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0011_auto_20161215_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
