# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyzer_core',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyzer_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller_name', models.CharField(blank=True, max_length=40)),
                ('controller_problem_settins', models.CharField(choices=[('classification', 'classification'), ('regression', 'regression'), ('clustering', 'clustering')], default='classification', max_length=40)),
                ('controller_core_packages', models.CharField(choices=[('sklearn', 'sklearn'), ('lasagne', 'lasagne'), ('keras', 'keras'), ('theano', 'theano'), ('tensorflow', 'tensorflow'), ('torch', 'torch'), ('caffe', 'caffe')], default='scikit-learn', max_length=50)),
                ('controller_core_estimator', models.CharField(blank=True, choices=[('LogisticRegression', 'LogisticRegression'), ('Support Vector Machine', 'Support Vector Machine'), ('XgBoost', 'XgBoost')], default='LogisticRegression', max_length=50)),
                ('controller_core_parameters', models.CharField(blank=True, max_length=100)),
                ('controller_visual_tool', models.CharField(default='scatter', max_length=100)),
                ('controller_created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
