# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='controller_input_file_field',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='controller',
            name='controller_core_packages',
            field=models.CharField(blank=True, choices=[('sklearn', 'sklearn'), ('lasagne', 'lasagne'), ('keras', 'keras'), ('theano', 'theano'), ('tensorflow', 'tensorflow'), ('torch', 'torch'), ('caffe', 'caffe')], default='scikit-learn', max_length=50),
        ),
    ]
