# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzer', '0002_auto_20161225_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostProcessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postprocessor_name', models.CharField(default='test_postprocess', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PreProcessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preprocessor_name', models.CharField(default='test_preprocess', max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='controller',
            old_name='controller_problem_settins',
            new_name='controller_problem_settings',
        ),
        migrations.AlterField(
            model_name='controller',
            name='controller_core_estimator',
            field=models.CharField(blank=True, choices=[('LogisticRegression', 'LogisticRegression'), ('SVM', 'SVM'), ('XgBoost', 'XgBoost'), ('AlexNet', 'AlexNet'), ('GoogleNet', 'GoogleNet'), ('ResNet', 'ResNet')], default='LogisticRegression', max_length=50),
        ),
        migrations.AlterField(
            model_name='controller',
            name='controller_visual_tool',
            field=models.CharField(choices=[('scatter', 'scatter')], default='scatter', max_length=100),
        ),
    ]
