# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=250)),
                ('album_title', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=100)),
                ('album_logo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('datafile', models.FileField(upload_to=b'', verbose_name='datafile')),
                ('filetype', models.CharField(max_length=10)),
                ('tagkey', models.ManyToManyField(to='Audio.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=250)),
                ('is_favorite', models.BooleanField(default=False)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Audio.Album')),
            ],
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='tagkey',
        ),
        migrations.DeleteModel(
            name='Sound',
        ),
    ]
