# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0002_auto_20161114_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file_type',
            field=models.CharField(default='mp3', max_length=10),
        ),
    ]
