# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0003_song_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='datafile',
            field=models.FileField(upload_to='', verbose_name='datafile'),
        ),
    ]
