# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0004_auto_20161122_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
