# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0006_auto_20161122_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='song',
            name='song_lyrics',
            field=models.CharField(default='', max_length=6000),
        ),
        migrations.AlterField(
            model_name='album',
            name='tagkey',
            field=models.ManyToManyField(blank=True, to='Audio.Tag'),
        ),
        migrations.AddField(
            model_name='albumcomment',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Audio.Album'),
        ),
    ]
