# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0007_auto_20161123_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_lyric',
            field=models.TextField(default=''),
        ),
    ]
