# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0008_song_song_lyric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_lyric',
        ),
        migrations.AlterField(
            model_name='song',
            name='song_lyrics',
            field=models.TextField(default=''),
        ),
    ]
